// Generated by CoffeeScript 1.3.1
(function() {
  var css, head, heads, node, _i, _len;

  css = "td > div, div.Bk, body.editable, textarea {\n  font-family: Menlo, Monaco, DejaVu Sans Mono, Courier, monospace !important;\n}";

  try {
    node = document.createElement("style");
    node.type = "text/css";
    node.appendChild(document.createTextNode(css));
    heads = document.getElementsByTagName('head');
    for (_i = 0, _len = heads.length; _i < _len; _i++) {
      head = heads[_i];
      head.appendChild(node);
    }
  } catch (err) {
    try {
      console.log("Error applying GMail style: ");
      console.log(err);
      console.log(err.stack);
    } catch (err) {

    }
  }

}).call(this);
